# Generated by Django 6.0.1 on 2026-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
